<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
    'Calendar'                     => 'Calendario'                    , 
	'SINGLE_Calendar'              => 'Compito'                     , 
	'LBL_ADD_TASK'                 => 'Aggiungi Compito'            , 
	'LBL_ADD_EVENT'                => 'Aggiungi Evento'             , 
	'LBL_RECORDS_LIST'             => 'Vista per lista'             , 
	'LBL_EVENTS'                   => 'Eventi'                      , 
	'LBL_TODOS'                    => 'Compito'                     , 
	'LBL_CALENDAR_SETTINGS'        => 'Impostazioni calendario'     ,
	'LBL_CALENDAR_SHARING'         => 'Condividi calendario'        ,
	'LBL_DEFAULT_EVENT_DURATION'   => 'Durata evento predefinita'   ,
	'LBL_CALL'                     => 'Chiama'                      ,
	'LBL_OTHER_EVENTS'             => 'Altri eventi'                ,
	'LBL_MINUTES'                  => 'Minuti'                      ,
	'LBL_SELECT_USERS'             => 'Seleziona utenti'            ,
	'LBL_EVENT_OR_TASK'            => 'Evento / Compito'            ,
	'LBL_TASK_INFORMATION'         => 'Compito Informazione'        , 
    	'LBL_EVENT_INFORMATION'        => 'Dettagli evento'             ,
	'Subject'                      => 'Soggetto'                    , 
	'Start Date & Time'            => 'Orario e data inizio'        , 
	'Activity Type'                => 'Tipo attivit&agrave;'        , 
	'Send Notification'            => 'Invia notifica'              , 
	'Location'                     => 'Luogo'                       , 
	'End Date & Time'              => 'Data e Ora Fine'             ,
	'Visibility'		       => 'Visibilità'			,
	'Recurrence'		       => 'Ricorrenza'			,
	'Private'		       => 'Privato'			,
	'Public'		       => 'Pubblico'			,
	'LBL_ACTIVITY_TYPES'           => 'Tipo attivit&agrave;'        , 
	'LBL_CONTACTS_SUPPORT_END_DATE' => 'Data fine supporto'         , 
	'LBL_CONTACTS_BIRTH_DAY'       => 'Data di nascita'             , 
	'LBL_ADDED_CALENDARS'          => 'Aggiungi calendari'          ,
	'Call'                         => 'Chiamata'                    , 
	'Meeting'                      => 'Riunione'                    , 
	'Task'                         => 'Compito'                     ,
	'Planned'                      => 'Pianificato'                 , 
	'Completed'                    => 'Completato'                  , 
	'Pending Input'                => 'In attesa di input'          , 
	'Not Started'                  => 'Non Iniziato'                , 
	'Deferred'                     => 'Posticipato'                 ,
	'Held'			       => 'Svolto'			,
	'Not Held'		       => 'Non svolto'			,
	'Medium'                       => 'Medio'                       , 
	'LBL_CHANGE_OWNER'             => 'Cambia proprietario'         , 
	'LBL_EVENT'                    => 'Evento'                      , 
	'LBL_TASK'                     => 'Compito'                     , 
	'LBL_TASKS'		       => 'Compiti'			,
	'LBL_CALENDAR_VIEW'            => 'Visualizza calendario' 	, 
	'LBL_SHARED_CALENDAR'          => 'Calendario condiviso'        ,
	'LBL_DAY0'                     => 'Domenica'                    ,
	'LBL_DAY1'                     => 'Luned&igrave;'               ,
	'LBL_DAY2'                     => 'Marted&igrave;'              ,
	'LBL_DAY3'                     => 'Mercoled&igrave;'            ,
	'LBL_DAY4'                     => 'Gioved&igrave;'              ,
	'LBL_DAY5'                     => 'Venerd&igrave;'              ,
	'LBL_DAY6'                     => 'Sabato'                      ,
	'first'                        => 'Nome'                        ,
	'last'                         => 'Cognome'                     ,
	'LBL_DAY_OF_THE_MONTH'         => 'giorno del mese'             ,
	'LBL_ON'                       => 'attivo'                      ,
	'Daily'                        => 'Giornaliero'                 ,
	'Weekly'                       => 'Settimanale'                 ,
	'Monthly'                      => 'Mensile'                     ,
	'Yearly'                       => 'Annuale'                     ,
        'LBL_DEFAULT_STATUS_TYPE'      => 'Tipo e stato predefiniti'    ,
        'LBL_STATUS'                   => 'Stato'                       ,
        'LBL_TYPE'                     => 'Tipo'                        ,
	//Fixing colors for Shared Calendar and My Calendar
	'LBL_EDIT_COLOR' 	       => 'Modifica colore'		,
	'LBL_ADD_CALENDAR_VIEW'	       => 'Aggiungi vista calendario'   ,
	'LBL_SELECT_USER_CALENDAR'     => 'Selezionare utente calendario',
	'LBL_SELECT_CALENDAR_COLOR'    => 'Selezionare colore calendario',
	'LBL_EDITING_CALENDAR_VIEW'    => 'Modifica vista calendario'	,
	'LBL_DELETE_CALENDAR'	       => 'Elimina calendario'		,
	'LBL_SELECT_ACTIVITY_TYPE'     => 'Selezionare il tipo di attivit&agrave;',
	'Tasks' 		       => 'Compito'			,
	'LBL_SELECT_FIELDS_FOR_RANGE'  => 'Selezionare i campi per la gamma',
	'LBL_DUPLICATE_VIEW_EXIST'     => 'Vista calendario esistente'	,
    
    	// For Event Invitation
    	'LBL_ACTIVITY_NOTIFICATION'    => "Questa &egrave; una notifica che un'attivit&agrave; &egrave; stata assegnata all'utente",
    	'LBL_ACTIVITY_INVITATION'      => "Sei stato invitato ad una attivit&agrave;",
    	'LBL_DETAILS_STRING'	       => 'Dettagli'			,
    	'LBL_CREATED' 		       => 'creato'			,
    	'LBL_UPDATED' 		       => 'aggiornato'			,
   	'Due Date' 		       => 'Scadenza'			,
    	'Priority'			=> 'Priorit&agrave;'		,
    	'Related To' 			=> 'Relativi a'			,
    	'LBL_CONTACT_LIST' 		=> 'Elenco dei contatti'	,
    	'LBL_APP_DESCRIPTION' 		=> 'Descrizione',
    	'LBL_REGARDS_STRING' 		=> 'Grazie e saluti',
    	'LBL_EVENT_INFORMATION' 	=> 'Dettagli evento',
	'LBL_UPDATED_INVITATION' 	=> 'Invito Aggiornato',
	'LBL_INVITATION' 		=> 'Invito',
	//Recurring Events
	'LBL_EDIT_RECURRING_EVENT'	=> 'Modifica evento ricorrente',
	'LBL_ALL_EVENTS_EDIT_INFO' 	=> 'Tutti gli eventi della serie saranno cambiati.</br>Saranno mantenute le eventuali modifiche apportate agli altri eventi.',
	'LBL_FUTURE_EVENTS_EDIT_INFO' 	=> 'Questo e tutti i seguenti eventi saranno cambiati.</br>Eventuali modifiche ad eventi futuri saranno persi.',
	'LBL_ONLY_THIS_EVENT_EDIT_INFO' => 'Tutti gli altri eventi della serie rimarranno le stesse.',
	'LBL_EDIT_RECURRING_EVENTS_INFO' => 'Vuoi salvare le modifiche per',
	
	'LBL_DELETE_RECURRING_EVENT' 	=> 'Elimina evento ricorrente',
	'LBL_ALL_EVENTS_DELETE_INFO'	=> 'Tutti gli eventi della serie saranno cancellati.',
	'LBL_FUTURE_EVENTS_DELETE_INFO' => 'Questo e tutti i seguenti eventi saranno cancellati.',
	'LBL_ONLY_THIS_EVENT_DELETE_INFO' => 'Tutti gli altri eventi della serie non saranno cancellati.',
	'LBL_DELETE_RECURRING_EVENTS_INFO' => 'Vuoi eliminare solo questo evento, tutti gli eventi della serie o anche gli eventi futuri della serie?',
	'LBL_ONLY_THIS_EVENT' 		=> 'Solo questo evento',
	'LBL_FUTURE_EVENTS' 		=> 'Anche gli eventi futuri',
	'LBL_ALL_EVENTS' 		=> 'Tutti gli eventi',

  	'SINGLE_Events' 		=> 'Eventi',
  	'LBL_IMPORT_RECORDS' 		=> 'Importazione dei record',
  	'LBL_RESULT' 			=> 'Risultato',
 	'LBL_FINISH' 			=> 'Fine',
  	'LBL_TOTAL_TASKS_IMPORTED' 	=> 'No. di attivit&agrave; importate correttamente ',
  	'LBL_TOTAL_TASKS_SKIPPED' 	=> 'No. di attivit&agrave; saltate poich&eacute; erano mancanti di una o pi&ugrave; richieste di campo.',
  	'LBL_TOTAL_EVENTS_IMPORTED' 	=> 'No. di eventi importati correttamente',
  	'LBL_TOTAL_EVENTS_SKIPPED' 	=> 'No. di eventi saltate poich&eacute; erano mancanti di una o pi&ugrave; richieste di campo.',
  	'ICAL_FORMAT' 			=> 'Formato iCal',
  	'LBL_LAST_IMPORT_UNDONE' 	=> 'La tua ultima importazione &egrave; stata annullata',
  	'LBL_UNDO_LAST_IMPORT' 		=> 'Annulla l\'ultima importazione',
  	'LBL_REMINDER_NOTIFICATION' 	=> 'Questo &egrave; un promemoria di notifica per l\'attivit&agrave;',
  	'LBL_SELECT_EVENT_TYPE' 	=> 'Tipo di attivit&agrave;',
  	'LBL_THIS_WEEK'			=> 'Questa settimana',
  	'LBL_ADD_TASK_AND_PRESS_ENTER' 	=> 'Aggiungi operazione e premi invio',


  	'LBL_JANUARY' => 'Gennaio',
  	'LBL_FEBRUARY' => 'Febbraio',
  	'LBL_MARCH' => 'Marzo',
  	'LBL_APRIL' => 'Aprile',
  	'LBL_MAY' => 'Maggio',
  	'LBL_JUNE' => 'Giugno',
  	'LBL_JULY' => 'Luglio',
  	'LBL_AUGUST' => 'Agosto',
  	'LBL_SEPTEMBER' => 'Settembre',
  	'LBL_OCTOBER' => 'Ottobre',
  	'LBL_NOVEMBER' => 'Novembre',
  	'LBL_DECEMBER' => 'Dicembre',
	'LBL_CLICK_HERE_TO_VIEW' => 'Clicca qui per vedere',

	'LBL_TOTAL_EVENTS_DUPLICATED' => 'Numero di eventi duplicati saltato',
	'LBL_TOTAL_TASKS_DUPLICATED' => 'Numero di compiti duplicati saltato',
);
$jsLanguageStrings = array(
	'LBL_ADD_EVENT_TASK'           => 'Aggiungi evento / compito'            , 
	'JS_TASK_IS_SUCCESSFULLY_ADDED_TO_YOUR_CALENDAR' => 'Il compito &egrave; stato aggiunto correttamente al tuo calendario',
	'LBL_CANT_SELECT_CONTACT_FROM_LEADS' => 'Impossibile selezionare i contatti correlati per lead',
        'JS_FUTURE_EVENT_CANNOT_BE_HELD' => 'Futuri eventi non possono essere trattenuti',
	
	//Calendar view label translation
	'LBL_MONTH' => 'Mese',
	'LBL_TODAY' => 'Oggi',
	'LBL_DAY' => 'Giorno',
	'LBL_WEEK' => 'Settimana',
	
	'LBL_SUNDAY' => 'Domenica',
	'LBL_MONDAY' => 'Luned&igrave;',
	'LBL_TUESDAY' => 'Marted&igrave;',
	'LBL_WEDNESDAY' => 'Mercoled&igrave;',
	'LBL_THURSDAY' => 'Gioved&igrave;',
	'LBL_FRIDAY' => 'Venerd&igrave;',
	'LBL_SATURDAY' => 'Sabato',
	
	'LBL_SUN' => 'Dom',
	'LBL_MON' => 'Lun',
	'LBL_TUE' => 'Mar',
	'LBL_WED' => 'Mer',
	'LBL_THU' => 'Gio',
	'LBL_FRI' => 'Ven',
	'LBL_SAT' => 'Sab',
	
	'LBL_JANUARY' => 'Gennaio',
	'LBL_FEBRUARY' => 'Febbraio',
	'LBL_MARCH' => 'Marzo',
	'LBL_APRIL' => 'Aprile',
	'LBL_MAY' => 'Maggio',
	'LBL_JUNE' => 'Giugno',
	'LBL_JULY' => 'Luglio',
	'LBL_AUGUST' => 'Agoto',
	'LBL_SEPTEMBER' => 'Settembre',
	'LBL_OCTOBER' => 'Ottobre',
	'LBL_NOVEMBER' => 'Novembre',
	'LBL_DECEMBER' => 'Dicembre',
	
	'LBL_JAN' => 'Gen',
	'LBL_FEB' => 'Feb',
	'LBL_MAR' => 'Mar',
	'LBL_APR' => 'Apr',
	'LBL_MAY' => 'Mag',
	'LBL_JUN' => 'Giu',
	'LBL_JUL' => 'Lug',
	'LBL_AUG' => 'Ago',
	'LBL_SEP' => 'Set',
	'LBL_OCT' => 'Ott',
	'LBL_NOV' => 'Nov',
	'LBL_DEC' => 'Dic',
	
	'LBL_ALL_DAY' => 'Tutti',
	//End
	
	//Fixing colors for Shared Calendar and My Calendar
	'JS_CALENDAR_VIEW_COLOR_UPDATED_SUCCESSFULLY' => 'Colore calendario aggiornato con successo',
	'JS_CALENDAR_VIEW_DELETE_CONFIRMATION' => 'Sei sicuro di voler eliminare questa vista calendario?',
	'JS_CALENDAR_VIEW_ADDED_SUCCESSFULLY' => 'Vista calendario aggiunta con successo',
	'JS_CALENDAR_VIEW_DELETED_SUCCESSFULLY' => 'Vista calendario eliminata correttamente',
	'JS_NO_CALENDAR_VIEWS_TO_ADD' => 'Non ci sono viste calendar da aggiungere',
	'JS_EDIT_CALENDAR' => 'Modifica calendario',

  'LBL_TOMORROW' => 'Domani',
  'JS_EVENT_UPDATED' => 'Evento aggiornato',
  'JS_NO_EVENTS_F0R_THE_DAY' => 'Nessun evento per il giorno',
  'LBL_AGENDA' => 'Agenda',
  'JS_CALENDAR_VIEW_YOU_ARE_EDITING_NOT_FOUND' => 'Vista calendario non trovata',
  'JS_DELETE' => 'Elimina',
  'JS_EDIT' => 'Modifica',
  'JS_MARK_AS_HELD' => 'Trattenuta',
  'JS_CREATE_FOLLOW_UP' => 'Crea azione supplementare',
  'JS_RECURRING_EVENT' => 'Evento ricorrente',
  'JS_DETAILS' => 'Pi&ugrave dettagli',


  'JS_CHECK_START_AND_END_DATE' => 'La fine data ed ora devono essere maggiori o uguali alla data di inizio e dell\'ora',
  'JS_CHECK_START_AND_END_DATE_SHOULD_BE_GREATER' => 'La fine data ed ora devono essere maggiori della data di inizio e dell\'ora',

);
