<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'SINGLE_Documents'             => 'Documento'                   , 
	'Documents'                    => 'Documenti'                   ,
	'LBL_ADD_RECORD'               => 'Aggiungi Documento'                , 
	'LBL_RECORDS_LIST'             => 'Lista documenti'              , 
	'LBL_NOTE_INFORMATION'         => 'Informazioni Base'           , 
	'LBL_FILE_INFORMATION'         => 'Informazioni file'           , 
	'LBL_DESCRIPTION'              => 'Descrizione'                 , 
	'Title'                        => 'Titolo'                      , 
	'File Name'                    => 'Nome file'                   , 
	'Note'                         => 'Note'                        , 
	'File Type'                    => 'Tipo file'                   , 
	'File Size'                    => 'Grandezza'                   , 
	'Download Type'                => 'Tipo download'               , 
	'Version'                      => 'Versione'                    , 
	'Active'                       => 'Attivo'                      , 
	'Download Count'               => 'Conteggio download'          , 
	'Folder Name'                  => 'Nome cartella'               , 
	'Document No'                  => 'Numero documento'           , 
	'Last Modified By'             => 'Ultima modifica di '            , 
	'LBL_FOLDER_HAS_DOCUMENTS'     => 'Sposta i documenti prima di cancellare la cartella', 
	'LBL_DOWNLOAD_FILE'            => 'Download file'               , 
	'LBL_CHECK_FILE_INTEGRITY'     => 'Controllo di integrit&agrave;'     , 
	'LBL_INTERNAL'                 => 'Interno'                     , 
	'LBL_EXTERNAL'                 => 'Esterno'                     , 
	'LBL_MAX_UPLOAD_SIZE'          => 'Dimensione massima upload'         , 
	'LBL_MOVE'                     => 'Muovi'                       , 
	'LBL_ADD_FOLDER'               => 'Aggiungi cartella'           , 
	'LBL_FOLDERS_LIST'             => 'Lista cartelle'                , 
	'LBL_FOLDERS'                  => 'Cartelle'                     , 
	'LBL_DOCUMENTS_MOVED_SUCCESSFULLY' => 'Documenti spostati con successo', 
	'LBL_DENIED_DOCUMENTS'         => 'Documenti privati'            , 
	'MB'                           => 'MB'                          , 
	'LBL_ADD_NEW_FOLDER'           => 'Aggiungi cartella'           , 
	'LBL_FOLDER_NAME'              => 'Nome cartella'               , 
	'LBL_FOLDER_DESCRIPTION'       => 'Descrizione cartella'          , 
	'LBL_FILE_AVAILABLE'           => 'I file sono disponibili per il download', 
	'LBL_FILE_NOT_AVAILABLE'       => 'Questo documento non &egraveM disponibile per il download', 
    'LBL_VIEW_FILE' => 'Visualizza File',
    'LBL_PREVIEW_NOT_AVAILABLE' => 'Anteprima non disponibile',
    'LBL_VIEW_FILE' => 'Visualizza File',
    'LBL_PREVIEW_NOT_AVAILABLE' => 'Anteprima non disponibile',
    'LBL_INTERNAL_DOCUMENT_TYPE' =>'Documento interno',
    'LBL_EXTERNAL_DOCUMENT_TYPE' =>'URL esterno',
    'LBL_WEBDOCUMENT_TYPE' =>'Documento Web',
    'LBL_DRAG_&_DROP_FILE_HERE' => 'Drag & Drop il file qui',
    'LBL_WEB' => 'Tela',
    'LBL_UPLOAD_DOCUMENT_TO_VTIGER' => 'Carica documenti su Vtiger',
    'LBL_ROOT' => 'Radice',
    'LBL_AUTHORIZE' => 'Autorizzare',
    'LBL_DOCUMENT_SOURCE' => 'Origine documento',
    'LBL_FILE_URL' => 'Url File',

  'LBL_EMAIL_FILE_AS_ATTACHMENT' => 'Allega file all\'e-mail',
  'LBL_UPLOAD_TO' => 'Caricare',
  'LBL_NEW_DOCUMENT' => 'Nuovo Documento',
  'LBL_VTIGER' => 'Vtiger',
  'LBL_CREATE_YOUR_OWN' => 'Creare il proprio',
  'LBL_SHARE_DOCUMENT' => 'Condividere un documento',
  'LBL_UPLOAD_TO_VTIGER' => 'Caricare su Vtiger',
  'LBL_UPLOAD' => 'Caricare',
  'LBL_SELECT_FILE_FROM_COMPUTER' => 'Selezionare il file dal mio computer',
  'LBL_FILE_UPLOAD' => 'Upload di file',
  'LBL_LINK_EXTERNAL_DOCUMENT' => 'Link esterni al documento',
  'LBL_TO_SERVICE' => 'Di %s',
  'LBL_FROM_SERVICE' => 'Da %s',
  'LBL_CREATE_NEW' => 'Creare Nuova %s',
	'LBL_SELECT_A_FOLDER_TO_MOVE' => 'Selezionare la cartella in cui spostare i documenti',
);
$jsLanguageStrings = array(
	'JS_NEW_FOLDER'                => 'Nuova cartella'                  , 
	'JS_MOVE_DOCUMENTS'            => 'Sposta documenti'              , 
	'JS_ARE_YOU_SURE_YOU_WANT_TO_MOVE_DOCUMENTS_TO' => 'Sei sicuro di voler spostare il file?', 
	'JS_FOLDER'                    => 'cartella'                      , 
	'JS_OPERATION_DENIED'          => 'Operazione negata'            , 
	'JS_FOLDER_IS_NOT_EMPTY' => 'Elimina / Sposta tutti i documenti contenuti nella cartella corrente prima di cancellarla',
	'JS_SPECIAL_CHARACTERS' => 'Caratteri speciali come',
	'JS_NOT_ALLOWED' => 'non sono ammessi',
    'JS_DELETE_AND_TRASH_FILE_IN_DRIVE' => 'Eliminare file e cestinati sul disco',
    'JS_FAILED_TO_UPLOAD_FILE' => 'Impossibile caricare il file',
    'JS_ARE_YOU_SURE_TO_REVOKE_ACCESS' => 'Sei sicuro di voler revocare l\'accesso?',
    'JS_ACCESS_REVOKED' => 'Accesso revocato',
    'JS_DELETE_AND_TRASH_FILE_IN_DROPBOX' => 'Eliminare file e cestinati in dropbox',
    'JS_UPLOAD_SUCCESSFUL' => 'File caricato con successo',
    'JS_UPLOAD_FAILED' => 'Caricamento file non riuscito',
    'JS_DOCUMENT_CREATED' => 'Documento creato',
    'JS_DOCUMENT_CREATION_FAILED' => 'La creazione del documento &egrave; fallita',
);
