<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'Events'                       => 'Eventi'                      , 
	'SINGLE_Events'                => 'Evento'                      , 
	'LBL_ADD_RECORD'               => 'Aggiungi Evento'                   , 
	'LBL_RECORDS_LIST'             => 'Visualizza Lista'                   , 
	'LBL_EVENTS'                   => 'Eventi'                      , 
	'LBL_TODOS'                    => 'Compito'                     , 
	'LBL_HOLD_FOLLOWUP_ON'         => 'Attiva azione'          ,
    'LBL_CREATE_FOLLOWUP_EVENT'    => 'Crea azione su evento'        ,
	'LBL_EVENT_INFORMATION'        => 'Dettagli evento'               , 
	'LBL_RECURRENCE_INFORMATION'   => 'Dettagli ricorrenti'          , 
	'LBL_RELATED_TO'               => 'Relativo a'                  ,
    'Related To'                   => 'Relativo a'                  ,
	'Start Date & Time'            => 'Data e Ora inizio'           , 
	'Recurrence'                   => 'Ricorrenza'                  , 
	'Send Notification'            => 'Invia notifica'           , 
	'Location'                     => 'Localit&agrave;'                    , 
	'Send Reminder'                => 'Invia promemoria'               , 
	'End Date & Time'              => 'Data e Ora Fine'             , 
    'End Date'                     => 'Data e Ora Fine'             , 
	'Activity Type'                => 'Tipo Attivit&agrave;'        , 
	'Visibility'                   => 'Visibilit&agrave;'                  , 
	'Private'                      => 'Privato'                     , 
	'Public'                       => 'Pubblico'                    , 
	'Call'                         => 'Chiamata'                    , 
	'Meeting'                      => 'Riunione'                    , 
	'Planned'                      => 'Pianificato'                 , 
	'Held'                         => 'Tenuto'                      , 
	'Not Held'                     => 'Non Tenuto'                  , 
	'LBL_DAYS'                     => 'Giorni'                        , 
	'LBL_HOURS'                    => 'Ore'                       , 
	'LBL_DAYS_TYPE'                => 'Giorno/i'                      ,
	'LBL_WEEKS_TYPE'               => 'Settimana/e'                     ,
	'LBL_MONTHS_TYPE'              => 'Mese/i'                    ,
	'LBL_YEAR_TYPE'                => 'Anno'                        ,
	'LBL_FIRST'                    => 'Nome'                       ,
	'LBL_LAST'                     => 'Cognome'                        ,
	'LBL_SM_SUN'                   => 'Dom'                         ,
	'LBL_SM_MON'                   => 'Lun'                         ,
	'LBL_SM_TUE'                   => 'Mar'                         ,
	'LBL_SM_WED'                   => 'Mer'                         ,
	'LBL_SM_THU'                   => 'Gio'                         ,
	'LBL_SM_FRI'                   => 'Ven'                         ,
	'LBL_SM_SAT'                   => 'Sab'                         ,
	'LBL_DAY0'                     => 'Domenica'                      ,
	'LBL_DAY1'                     => 'Luned&igrave;'                      ,
	'LBL_DAY2'                     => 'Marted&igrave;'                     ,
	'LBL_DAY3'                     => 'Mercoled&igrave;'                   ,
	'LBL_DAY4'                     => 'Gioved&igrave;'                    ,
	'LBL_DAY5'                     => 'Venerd&igrave;'                      ,
	'LBL_DAY6'                     => 'Sabato'                    ,
	'Daily'                        => 'Giorno/i'                      ,
	'Weekly'                       => 'Settimana/e'                     ,
	'Monthly'                      => 'Mese/i'                    ,
	'Yearly'                       => 'Anno'                        ,
	'LBL_REPEATEVENT'              => 'Una volta ogni'        ,
	'LBL_UNTIL'                    => 'Fino a'                       ,
	'LBL_DAY_OF_THE_MONTH'         => 'giorno del mese'            ,
	'LBL_ON'                       => 'su'                          ,
	'LBL_CALENDAR_VIEW'            => 'Vista calendario'               , 
	'LBL_INVITE_USER_BLOCK'        => 'Invita'                      ,
	'LBL_INVITE_USERS'             => 'Invita utenti'                ,
	'LBL_INVITE_PEOPLE'			   => 'Invita persone',

  'INVITATION' => ' Invito ',
  'Busy' => 'Occupato',

);
