<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'LBL_IMPORT_STEP_1'            => 'Step 1'                      , 
	'LBL_IMPORT_STEP_1_DESCRIPTION' => 'Seleziona file'                 , 
	'LBL_IMPORT_SUPPORTED_FILE_TYPES' => '	Tipo file supportati: .CSV, .VCF', 
	'LBL_IMPORT_STEP_2'            => 'Step 2'                      , 
	'LBL_IMPORT_STEP_2_DESCRIPTION' => 'Specifica formato'              , 
	'LBL_FILE_TYPE'                => 'Tipo file'                   , 
	'LBL_CHARACTER_ENCODING'       => 'Codifica carattere'          , 
	'LBL_DELIMITER'                => 'Delimitatore:'               , 
	'LBL_HAS_HEADER'               => 'Ha una intestazione' , 
	'LBL_IMPORT_STEP_3'            => 'Step 3'                      , 
	'LBL_IMPORT_STEP_3_DESCRIPTION' => 'Gestione duplica record'   , 
	'LBL_IMPORT_STEP_3_DESCRIPTION_DETAILED' => 'Selezionare questa opzione per abilitare e impostare i criteri di unione duplicati', 
	'LBL_SPECIFY_MERGE_TYPE'       => 'Seleziona come devono essere gestiti i record duplicati', 
	'LBL_SELECT_MERGE_FIELDS'      => 'Seleziona i campi corrispondenti per trovare i record duplicati', 
	'LBL_AVAILABLE_FIELDS'         => 'Campi disponibili'           , 
	'LBL_SELECTED_FIELDS'          => 'Campi su cui effettuare la corrispondenza', 
	'LBL_NEXT_BUTTON_LABEL'        => 'Prossimo'                    , 
	'LBL_IMPORT_STEP_4'            => 'Step 4'                      , 
	'LBL_IMPORT_STEP_4_DESCRIPTION' => 'Collegare le colonne ai campi del modulo', 
	'LBL_FILE_COLUMN_HEADER'       => 'Intestazione'                      , 
	'LBL_ROW_1'                    => 'Riga 1'                       , 
	'LBL_CRM_FIELDS'               => 'Campi CRM'                  , 
	'LBL_DEFAULT_VALUE'            => 'Valore di default'               , 
	'LBL_SAVE_AS_CUSTOM_MAPPING'   => 'Salva come collegamento personalizzato '     , 
	'LBL_IMPORT_BUTTON_LABEL'      => 'Importa'                     , 
	'LBL_RESULT'                   => 'Risultato'                      , 
	'LBL_TOTAL_RECORDS_IMPORTED'   => 'Record importati correttamente', 
	'LBL_NUMBER_OF_RECORDS_CREATED' => 'Record creati'             , 
	'LBL_NUMBER_OF_RECORDS_UPDATED' => 'Record sovrascritti'         , 
	'LBL_NUMBER_OF_RECORDS_SKIPPED' => 'Record saltati'             , 
	'LBL_NUMBER_OF_RECORDS_MERGED' => 'Record uniti'              , 
	'LBL_TOTAL_RECORDS_FAILED'     => 'Record falliti durante l\'importazione'    , 
	'LBL_IMPORT_MORE'              => 'Importa di pi&ugrave;'       , 
	'LBL_VIEW_LAST_IMPORTED_RECORDS' => 'Ultimi record importati'       , 
	'LBL_UNDO_LAST_IMPORT'         => 'Annulla l\'ultima importazione', 
	'LBL_FINISH_BUTTON_LABEL'      => 'Fine'                        , 
	'LBL_UNDO_RESULT'              => 'Annulla risultato importazione'          , 
	'LBL_TOTAL_RECORDS'            => 'Numero totale di record'     , 
	'LBL_NUMBER_OF_RECORDS_DELETED' => 'Numero di record cancellati'   , 
	'LBL_OK_BUTTON_LABEL'          => 'Ok'                          , 
	'LBL_IMPORT_SCHEDULED'         => 'Importazione pianificata'            , 
	'LBL_RUNNING'                  => 'Esecuzione'                     , 
	'LBL_CANCEL_IMPORT'            => 'Cancella importazione'               , 
	'LBL_ERROR'                    => 'Errore:'                     , 
	'LBL_CLEAR_DATA'               => 'Pulisci Data'                  , 
	'ERR_UNIMPORTED_RECORDS_EXIST' => 'Impossibile importare pi&ugrave; dati con questo processo. Si prega di avviare una nuova importazione.', 
	'ERR_IMPORT_INTERRUPTED'       => 'L\'importazione corrente &egrave; stata interrotta. Per favore riprova pi&ugrave; tardi', 
	'ERR_FAILED_TO_LOCK_MODULE'    => 'Impossibile bloccare il modulo per l\'importazione. Riprovare più tardi', 
	'LBL_SELECT_SAVED_MAPPING'     => 'Selezione collegamenti salvata'        , 
	'LBL_IMPORT_ERROR_LARGE_FILE'  => 'Errore importazione per file di grandi dimensioni '    ,
	'LBL_FILE_UPLOAD_FAILED'       => 'Upload file fallito'          ,
	'LBL_IMPORT_CHANGE_UPLOAD_SIZE' => 'Cambia dimensioni upload da importare'   ,
	'LBL_IMPORT_DIRECTORY_NOT_WRITABLE' => 'La directory per l\'importazione non &egrave; scrivibile',
	'LBL_IMPORT_FILE_COPY_FAILED'  => 'Copia importazione file fallita'     ,
	'LBL_INVALID_FILE'             => 'File non valido'                , 
	'LBL_NO_ROWS_FOUND'            => 'Nessuna riga trovata'               , 
	'LBL_SCHEDULED_IMPORT_DETAILS' => 'L\'importazione &egrave; stata pianificata ed inizier&agrave; entro 15 minuti. Riceverai una e-mail al termine dell\'importazione.  <br> <br>
										Assicurati che il server di posta in uscita ed il tuo indirizzo e-mail siano configurati per ricevere una notifica via e-mail', 
	'LBL_DETAILS'                  => 'Dettagli'                     ,
	'skipped'                      => 'Record saltati'             , 
	'failed'                       => 'Record falliti'              , 
    
        'LBL_IMPORT_LINEITEMS_CURRENCY'=> 'Valuta (voci)',

	'LBL_SKIP_THIS_STEP' => 'Ignorare questo passaggio',
	'LBL_UPLOAD_ICS' => 'Carica file ICS',
	'LBL_ICS_FILE' => 'ICS File',
	'LBL_IMPORT_FROM_ICS_FILE' => 'Importa da file ICS',
	'LBL_SELECT_ICS_FILE' => 'Seleziona il file ICS',

  'LBL_USE_SAVED_MAPS' => 'Utilizzare collegamenti salvati',
  'LBL_IMPORT_MAP_FIELDS' => 'Collega le colonne ai campi CRM',
  'LBL_UPLOAD_CSV' => 'Caricare il file CSV',
  'LBL_UPLOAD_VCF' => 'Caricare file VCF',
  'LBL_DUPLICATE_HANDLING' => 'Gestire i duplicati',
  'LBL_FIELD_MAPPING' => 'Collegamenti nel campo',
  'LBL_IMPORT_FROM_CSV_FILE' => 'Importazione da file CSV',
  'LBL_SELECT_IMPORT_FILE_FORMAT' => 'Dove vorresti importare?',
  'LBL_CSV_FILE' => 'File CSV',
  'LBL_VCF_FILE' => 'File VCF',
  'LBL_GOOGLE' => 'Google',
  'LBL_IMPORT_COMPLETED' => 'Importazione Completata',
  'LBL_IMPORT_SUMMARY' => 'Riepilogo di importazione',
  'LBL_DELETION_COMPLETED' => 'Cancellazione completata',
  'LBL_TOTAL_RECORDS_SCANNED' => 'Totale record acquisiti',
  'LBL_SKIP_BUTTON' => 'Saltare',
  'LBL_DUPLICATE_RECORD_HANDLING' => 'Duplica il record di movimentazione',
  'LBL_IMPORT_FROM_VCF_FILE' => 'Importazione da file VCF',
  'LBL_SELECT_VCF_FILE' => 'Selezionare file VCF',
  'LBL_DONE_BUTTON' => 'Fatto',
  'LBL_DELETION_SUMMARY' => 'Eliminare riepilogo',

);
