<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'Products'                     => 'Prodotti'                    , 
	'SINGLE_Products'              => 'Prodotto'                    , 
	'LBL_ADD_RECORD'               => 'Aggiungi Prodotto'           , 
	'LBL_RECORDS_LIST'             => 'Lista prodotti'               , 
	'LBL_PRODUCT_INFORMATION'      => 'Informazioni prodotto'       , 
	'LBL_IMAGE_INFORMATION'        => 'Informazioni immagine prodotto:', 
	'LBL_STOCK_INFORMATION'        => 'Informazioni disponibilit&agrave;:'         , 
	'LBL_MORE_CURRENCIES'          => 'Altre valute'                , 
	'LBL_PRICES'                   => 'Prezzo prodotti'             , 
	'LBL_PRICE'                    => 'Prezzo'                      , 
	'LBL_RESET_PRICE'              => 'Annulla prezzo'              , 
	'LBL_RESET'                    => 'Annulla'                     , 
	'LBL_ADD_TO_PRICEBOOKS'        => 'Aggiungi ai listini'           , 
	'Product No'                   => 'Num. prodotto'                , 
	'Part Number'                  => 'Numero di serie'             , 
	'Product Active'               => 'Prodotto attivo'             , 
	'Manufacturer'                 => 'Produttore'                  , 
	'Product Category'             => 'Categoria prodotto'          , 
	'Website'                      => 'Sito Web'                    , 
	'Mfr PartNo'                   => 'Numero di serie produttore'  , 
	'Vendor PartNo'                => 'Numero di serie fornitore'   , 
	'Usage Unit'                   => 'Unit&agrave; utilizzo'      , 
	'Handler'                      => 'Responsabile'                , 
	'Reorder Level'                => 'Livello riordino'            , 
	'Tax Class'                    => 'Classe delle tasse'             , 
	'Serial No'                    => 'Numero di serie'             , 
	'Qty In Stock'                 => 'Quantit&agrave; disponibile'    , 
	'Product Sheet'                => 'Specifiche prodotto'         , 
	'Qty In Demand'                => 'Quantit&agrave;  richiesta', 
	'GL Account'                   => 'Codice contabile'            , 
	'Product Image'                => 'Immagine prodotto'           , 
	'Unit Price'                   => 'Prezzo unitario'             , 
	'Commission Rate'              => 'Tasso commissione (%)'       , 
	'Qty/Unit'                     => 'Quantit&agrave;/Unit&agrave;', 
	'--None--'                     => '--Nessuno--'                 , 
	'Hardware'                     => 'Hardware'                    , 
	'Software'                     => 'Software'                    , 
	'CRM Applications'             => 'Applicazioni CRM'            , 
	'300-Sales-Software'           => '300-Vendita-Software'        , 
	'301-Sales-Hardware'           => '301-Vendita-Hardware'        , 
	'302-Rental-Income'            => '302-Noleggi-Software'        , 
	'303-Interest-Income'          => '303-Interessi'               , 
	'304-Sales-Software-Support'   => '304-Vendite-Supporto-Software', 
	'305-Sales Other'              => '305-Vendite-Altro'           , 
	'306-Internet Sales'           => '306-Vendite-Internet'        , 
	'307-Service-Hardware Labor'   => '307-Servizi-Riparazione-Hardware', 
	'308-Sales-Books'              => '308-Vendite-Libri'           , 
	'Box'                          => 'Scatola'                         , 
	'Carton'                       => 'Cartone'                     , 
	'Caton'                        => 'Cartone'                     , 
	'Dozen'                        => 'Dozzina'                       , 
	'Each'                         => 'Ogni'                        , 
	'Hours'                        => 'Ore'                         , 
	'Impressions'                  => 'Impressioni'                 , 
	'Lb'                           => 'Lb'                          , 
	'M'                            => 'M'                           , 
	'Pack'                         => 'Pacco'                       , 
	'Pages'                        => 'Pagine'                      , 
	'Pieces'                       => 'Pezzi'                       , 
	'Reams'                        => 'Risme'                       , 
	'Sheet'                        => 'Foglio'                      , 
	'Spiral Binder'                => 'Raccoglitore a spirale '     , 
	'Sq Ft'                        => 'Sq Ft'                       , 
	'LBL_CONVERSION_RATE'          => 'Tasso di conversione'             ,
    'LBL_PRODUCTSMOD_DISABLED'     => 'Abilita il Modulo Prodotti per visualizzare i prodotti',
	'LBL_SHOW_BUNDLE_IN_INVENTORY' => 'Mostra articoli per imballaggio fattura/quotazioni/offerta Ordine/Ordine di Acquisto',
	'LBL_BUNDLE_TOTAL_COST' => 'Costo totale dell\'imballaggio',
	'LBL_UPDATE_BUNDLE_PRICE' => 'Aggiornamento prezzo imballaggio',

  'LBL_PRODUCT_NAME' => 'Nome del prodotto',
  'LBL_PRICE_QUANTITY' => 'Prezzo x quantit&agrave;',

);

$jsLanguageStrings = array(
	'JS_SUB_PRODUCTS_WILL_BE_SHOWN_IN_INVENTORY' => 'I prodotti secondari saranno visualizzati nell\'inventario',
	'JS_SUB_PRODUCTS_WILL_NOT_BE_SHOWN_IN_INVENTORY' => 'I prodotti secondari non saranno visualizzati nell\'inventario',
	'JS_SUCCESSFULLY_CHANGED_BUNDLE_COST' => 'Costo totale dell\'imballaggio cambiato con successo',
	'JS_DELETION_OR_IN_ACTIVATION_CHILD_PRODUCT_MESSAGE' => 'Questo prodotto fa parte di un pacchetto di prodotti. Il prezzo del pacchetto rimane invariato quando una voce imballaggio viene eliminata o inattivata. Sei sicuro di voler continuare?',
);
