<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'Reports'                      => 'Report'                     ,
	'SINGLE_Reports'               => 'Report'                      ,
	'LBL_FOLDER_NOT_EMPTY'         => 'La cartella non &egrave; vuota'         ,
	'LBL_MOVE_REPORT'              => 'Sposta Report'               ,
	'LBL_CUSTOMIZE'                => 'Personalizza'                ,
	'LBL_REPORT_EXPORT_EXCEL'      => 'Esporta in Excel'                ,
	'LBL_REPORT_PRINT'             => 'Stampa'                      ,
	'LBL_STEP_1'                   => 'Step 1'                      ,
	'LBL_STEP_2'                   => 'Step 2'                      ,
	'LBL_STEP_3'                   => 'Step 3'                      ,
	'LBL_REPORT_DETAILS'           => 'Dettagli Report'             ,
	'LBL_SELECT_COLUMNS'           => 'Seleziona Colonne'           ,
	'LBL_FILTERS'                  => 'Filtri'                      ,
	'LBL_FOLDERS'                  => 'Cartelle'                     ,
	'LBL_ADD_NEW_FOLDER'           => 'Aggiungi una nuova cartella' ,
	'LBL_FOLDER_NAME'              => 'Nome cartella'                 ,
	'LBL_FOLDER_DESCRIPTION'       => 'Descrizione cartella'          ,
	'LBL_WRITE_YOUR_DESCRIPTION_HERE' => 'Inserisci una descrizione'           ,
	'LBL_DUPLICATES_EXIST'         => 'Duplica esistenti'            ,
	'LBL_FOLDERS_LIST'             => 'Lista cartelle'                ,
	'LBL_DENIED_REPORTS'           => 'Report negati'              ,
	'LBL_NO_OF_RECORDS'            => 'Totale record: '           , 
	'LBL_MORE_RECORDS_TXT'=>'Di seguito sono mostrati solo 500 record. Si prega di esportare per vedere tutti i record',
	'LBL_ADD_RECORD'               => 'Aggiungi Report'                  ,
	'LBL_ADD_FOLDER'               => 'Aggiungi Cartella'                  ,
	'LBL_REPORT_DELETE_DENIED'     => 'Permesso negato per cancellare i lreport',
	'LBL_FOLDER_CAN_NOT_BE_DELETED' => 'Questa cartella non può essere cancellata',
	'LBL_REPORTS_LIST'             => 'Lista Report'                ,
	'LBL_REPORT_NAME'              => 'Nome Report'                 ,
	'LBL_REPORT_FOLDER'            => 'Cartella Report'             ,
	'LBL_DESCRIPTION'              => 'Descrizione'                 ,
	'PRIMARY_MODULE'               => 'Modulo primario'              ,
	'LBL_SELECT_RELATED_MODULES'   => 'Seleziona moduli correlati'      ,
	'LBL_MAX'                      => 'Massimo'                     ,
	'LBL_NEXT'                     => 'Prossimo'                    ,
	'LBL_REPORTS'                  => 'Lista Report'                ,
	'LBL_GROUP_BY'                 => 'Gruppo di'                    ,
	'LBL_SORT_ORDER'               => 'Ordinamento'                  ,
	'LBL_ASCENDING'                => 'Ascendente'                  ,
	'LBL_DESCENDING'               => 'Discendente'                 ,
	'LBL_CALCULATIONS'             => 'Calcoli'                     ,
	'LBL_COLUMNS'                  => 'Colonne'                     ,
	'LBL_SUM_VALUE'                => 'Somma'                       ,
	'LBL_AVERAGE'                  => 'Media'                       ,
	'LBL_LOWEST_VALUE'             => 'Valore pi&ugrave; basso'     ,
	'LBL_HIGHEST_VALUE'            => 'Valore pi&ugrave; alto'               ,
	'LBL_GENERATE_REPORT'          => 'Salva e genera rapporto'     ,
	'LBL_SUM'                      => 'Somma'                       ,
	'LBL_AVG'                      => 'Media'                       ,
	'LBL_MIN'                      => 'Minimo'                      ,
	'LBL_FIELD_NAMES'              => 'Nomi dei Campi'              ,
	'LBL_REPORT_CSV'               => 'Esporta CSV'                  ,
	'LBL_VIEW_DETAILS'             => 'Visualizza dettagli'                ,
	'LBL_GENERATE_NOW'             => 'Genera adesso'                ,
	'Report Name'                  => 'Nome Report'                 ,
	'Account and Contact Reports'  => 'Report Aziende e Contatti'   ,
	'Lead Reports'                 => 'Report Lead'                 ,
	'Potential Reports'            => 'Report Opportunit&agrave;'   ,
	'Activity Reports'             => 'Report Attivit&agrave;'      ,
	'HelpDesk Reports'             => 'Report Ticket di Assistenza Clienti',
	'Product Reports'              => 'Report Prodotti'             ,
	'Quote Reports'                => 'Report Preventivi'           ,
	'PurchaseOrder Reports'        => 'Report Ordini di Acquisto'   ,
	'SalesOrder Reports'           => 'Report Ordini di Vendita'    ,
	'Invoice Reports'              => 'Report Fatture'              ,
	'Campaign Reports'             => 'Report Campagne'             ,
	'Contacts by Accounts'         => 'Contatti per Aziende'        ,
	'Contacts without Accounts'    => 'Contatti senza Aziende'      ,
	'Contacts by Potentials'       => 'Contatti per Opportunit&agrave;',
	'Contacts related to Accounts' => 'Contatti collegati alle Aziende',
	'Contacts not related to Accounts' => 'Contatti non collegati alle Aziende',
	'Contacts related to Potentials' => 'Contatti collegati alle Opportunit&agrave;',
	'Lead by Source'               => 'Lead per fonte'              ,
	'Lead Status Report'           => 'Report Lead per stato'       ,
	'Potential Pipeline'           => 'Andamento Opportunit&agrave;',
	'Closed Potentials'            => 'Opportunit&agrave; Chiuse'   ,
	'Potential that have Won'      => 'Opportunit&agrave;  Vinte'   ,
	'Tickets by Products'          => 'Ticket per Prodotti'         ,
	'Tickets by Priority'          => 'Ticket per Priorit&agrave;'  ,
	'Open Tickets'                 => 'Ticket Aperti'               ,
	'Tickets related to Products'  => 'Ticket collegati ai Prodotti',
	'Tickets that are Open'        => 'Ticket Aperti'              ,
	'Product Details'              => 'Dettagli Prodotti'           ,
	'Products by Contacts'         => 'Prodotti per Contatto'       ,
	'Product Detailed Report'      => 'Report dettagliato Prodotti' ,
	'Products related to Contacts' => 'Prodotti collegati ai Contatti',
	'Open Quotes'                  => 'Preventivi Aperti'           ,
	'Quotes Detailed Report'       => 'Report dettagliato Preventivi',
	'Quotes that are Open'         => 'Preventivi che sono Aperti'  ,
	'PurchaseOrder by Contacts'    => 'Ordini di Acquisto per Contatti',
	'PurchaseOrder Detailed Report' => 'Report dettagliato Ordini di Acquisto',
	'PurchaseOrder related to Contacts' => 'Ordini di Acquisto collegati ai Contatti',
	'Invoice Detailed Report'      => 'Report dettagliato Fatture'  ,
	'Last Month Activities'        => 'Attivit&agrave; del mese scorso',
	'This Month Activities'        => 'Attivit&agrave; di questo mese',
	'Campaign Expectations and Actuals' => 'Valori Attesi ed Effettivi delle Campagne',
	'SalesOrder Detailed Report'   => 'Report dettagliato Ordini di Vendita',
	'Email Reports'                => 'Report Email'               ,
	'Contacts Email Report'        => 'Report Email Contatti'       ,
	'Accounts Email Report'        => 'Report Email Organizzazioni'  ,
	'Leads Email Report'           => 'Report Email Lead'          ,
	'Vendors Email Report'         => 'Report Email Fornitori'        ,
	'Emails sent to Contacts'      => 'Mail inviate ai Contatti'     ,
	'Emails sent to Organizations' => 'Mail inviate alle Organizzazioni',
	'Emails sent to Leads'         => 'Mail inviate ai Lead'        ,
	'Emails sent to Vendors'       => 'Mail inviate ai Fornitori'      ,
	'LBL_PRINT_REPORT'             => 'Stampa Report'                ,
	'LBL_RECORDS'                  => 'Record'                     ,
	'LBL_LIMIT_EXCEEDED'           => 'Sono visualizzati solo 1000 record. Usa CSV o Esporta Excel per vedere tutti i record',
	'LBL_TOP'                      => 'Top'                         ,
	'LBL_ALL_REPORTS'              => 'Tutti i Report'                 ,
	'LBL_CALCULATION_CONVERSION_MESSAGE' => 'Il calcolo si basa sulle preferenze valuta del vostro CRM',

    //Schedule Reports
    'LBL_CREATING_REPORT'	=>	'Creazione di report',
	'LBL_EDITING_REPORT'	=>	'Modifica report',
	'LBL_SCHEDULE_REPORTS'	=>	'Pianificazione report',
	'LBL_AT_TIME'	=>	'Tempo',
	'LBL_DAILY'	=>	'Quotidiano',
	'LBL_WEEKLY'	=>	'Settimanale',
	'LBL_MONTHLY_BY_DATE'	=>	'Mensile per data',
	'LBL_YEARLY'	=>	'Annuale',
	'LBL_SPECIFIC_DATE'	=>	'Su specifica data',
	'LBL_CHOOSE_DATE'	=>	'Scegli data',
	'LBL_ON_THESE_DAYS'	=>	'In questi giorni',
	'LBL_SELECT_MONTH_AND_DAY'	=>	'Selezionare Mese e Data',
	'LBL_SELECTED_DATES'	=>	'Date selezionate',
	'LBL_EXCEEDING_MAXIMUM_LIMIT'	=>	'Limite massimo superato',
	'LBL_NEXT_TRIGGER_TIME'	=>	'Tempo di trigger su Avanti',
	'LBL_RUN_REPORT'	=>	'Esegui report',
	'LBL_SELECT_RECIEPIENTS'	=>	'Seleziona destinatari',
	'LBL_SPECIFIC_EMAIL_ADDRESS'	=>	'Invia a e-mail specifico',

    //Summary/Pivot Reports
    'LBL_CREATING_PIVOT_REPORT' => 'Crea report Pivot',
    'LBL_EDITING_PIVOT_REPORT' => 'Modifica report Pivot',
    'LBL_SELECT_PIVOT_FIELDS' => 'Selezionare campi Pivot',
    'LBL_SELECT_ROWS' => 'Selezionare Righe',
    'LBL_SELECT_DATA_FIELDS' => 'Selezionare campi Dati',
    'LBL_ADD_ROWS' => 'Aggiungere righe',
    'LBL_ADD_COLUMNS' => 'Aggiungere colonne',
    'LBL_ADD_DATA_FIELDS' => 'Aggiungere campi Dati',
    'LBL_PIVOT_FIELDS' => 'Seleziona campi Pivot',
    'LBL_RECORD_COUNT' => 'Conteggio Record',
    'LBL_SELECT_PIVOT_FIELDS_WARNING' => 'Attenzione: Si prega di selezionare almeno un campo riga, colonna o dati',
    'LBL_PIVOT_DATA_FIELDS_WARNING' => 'Attenzione: Nella colonna dati - le funzioni di aggregazione (somma, media, min e max) non devono ripetersi.',
    'LBL_MODIFY_CONDITIONS' => 'Modificare le condizioni',
    'LBL_PIVOT_PREVIEW_EX' => 'Anteprima report Pivot',

	//charts labels
	'LBL_SELECT_CHART_TYPE' => 'Selezionare il tipo di grafico',
	'LBL_CLICK_THROUGH_NOT_AVAILABLE' => 'Percentuale click non disponibile per come avete selezionato i moduli',
	'LBL_TOTAL_SUM_OF' => 'Somma totale di %s',
	'LBL_AVG_OF' => 'Medio di %s',
	'LBL_MIN_OF' => 'Minimo di %s',
	'LBL_MAX_OF' => 'Massimo di %s',
	'LBL_RECORD_COUNT' => 'Conteggio Record',
	'LBL_PIE_CHART' => 'Grafico a torta',
	'LBL_VERTICAL_BAR_CHART' => 'Barra verticale Grafico',
	'LBL_HORIZONTAL_BAR_CHART' => 'Grafico a barre orizzontali',
	'LBL_LINE_CHART' => 'Grafico a linee',
	'LBL_SELECT_CHART' => 'Selezionare Grafico',
	'LBL_CREATING_CHART_REPORT' => 'Creazione di report grafico',
	'LBL_EDITING_CHART_REPORT' => 'Modifica report grafico',
	'LBL_GENERATE_CHART' => 'Genera Grafico',
	'LBL_SELECT_GROUP_BY_FIELD' => 'Seleziona gruppo da campo',
	'LBL_SELECT_DATA_FIELD' => 'Selezionare campi dati',
	'LBL_MODIFY_CONDITION' => 'Modificare le condizioni',
	'LBL_PLEASE_SELECT_ATLEAST_ONE_GROUP_FIELD_AND_DATA_FIELD' => 'Si prega di selezionare almeno un campo gruupo e un campo di dati.',
	'LBL_FOR_BAR_GRAPH_AND_LINE_GRAPH_SELECT_3_MAX_DATA_FIELDS' => 'Per il grafico a barre o linee &egrave; possibile selezionare fino a 3 campi di dati.',
	'LBL_DETAIL_REPORT' =>	'Dettaglio Report',
	'LBL_PIVOT_REPORT'	=> 'Report Pivot',
	'LBL_CHARTS' => 'Grafici',
    //Schedule Reports - Mail Content
    'LBL_AUTO_GENERATED_REPORT_EMAIL' => 'Questa è una mail generata automaticamente ed inviata a nome di un report pianificato.',
    'LBL_PIN_CHART_TO_DASHBOARD' => 'Grafico Pin per la DashBoard',
    'LBL_FILE_FORMAT' => 'Formato del file',
    
    'Report Type' => 'Tipo di report',
    'tabular' => 'Tabellare',
    'summary' => 'Sommario',
    'pivot' => 'Pivot',
    'chart' => 'Grafico',
    'LBL_REPORTS_MOVED_SUCCESSFULLY'=>'Report spostati con successo.',
    'LBL_SAME_SOURCE_AND_TARGET_FOLDER'=>'La cartella di destinazione &egrave; la stessa cartella di origine.',
	'LBL_SEARCH_FOR_FOLDERS' => 'Ricerca per cartelle',
	'LBL_CHART_REPORT' => 'Diagramma del rapporto',
	'LBL_UNPIN_CHART_FROM_DASHBOARD' => 'Sblocca grafico dalla DashBoard',

  'LBL_SAME_LEVEL_ROLES' => 'Stesso livello di ruoli',
  'LBL_SUBORDINATE_ROLES' => 'Ruoli subordinati',
  'LBL_SHARE_REPORT' => 'Condividere Report',
  'LBL_SHARED_REPORTS' => 'Condividere i Report',
  'LBL_PINNED' => 'Fissato',
  'LBL_UNPINNED' => 'Sbloccato',


  'LBL_REPORTS_DELETED_SUCCESSFULLY' => 'Report eliminato con successo',

);
$jsLanguageStrings = array(
	'JS_DUPLICATE_RECORD'          => 'Report duplicato'            , 
	'JS_CALCULATION_LINE_ITEM_FIELDS_SELECTION_LIMITATION' => 'Limitazione: i campi dell\'elemento di riga (prezzo di listino, sconto e quantit&agrave;) possono essere utilizzati solo quando non sono selezionati in altri campi di calcolo.',
    'JS_CHART_PINNED_TO_DASHBOARD' => 'Grafico fissato sulla DashBoard',
    'JS_CHART_ALREADY_PINNED_TO_DASHBOARD' => 'Grafico già appuntato ad DashBoard',
	'JS_MOVE_REPORTS'=>'Spostare Report',
    'JS_SCHEDULED_DATE_TIME_ERROR' => 'La data e l\'orario programmati dovrebbero essere maggiori della data ed ora correnti',
	'JSLBL_PIN_CHART_TO_DASHBOARD' => 'Fissa grafico sulla Dashboard',
	'JSLBL_UNPIN_CHART_FROM_DASHBOARD' => 'Sblocca grafico dalla DashBoard',
	'JS_CHART_REMOVED_FROM_DASHBOARD' => 'Grafico rimosso dalla DashBoard',

  'JS_NO_CHART_DATA_AVAILABLE' => 'I dati non sono disponibili, si prega di verificare i campi selezionati',

);
